ShopingCart/Areas/Admin/Controllers/FootersController.cs
using System.Web.Mvc;
using Model;
using Service;
using ShopingCart.Common;

namespace ShopingCart.Areas.Admin.Controllers
{
    public class FootersController : BaseController
    {
		private FooterService footerService;
		public FootersController()
		{
			footerService = new FooterService();
		}
		
		[HasCredential(ActionId = 5)]
		public ActionResult Index()
        {
            return View(footerService.GetAll());
        }

		
		[HasCredential(ActionId = 6)]
		public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        [HasCredential(ActionId = 6)]
		public ActionResult Create([Bind(Include = "ID,Content,Status")] Footer footer)
        {
            if (ModelState.IsValid)
            {
				var result= footerService.Insert(footer);
				if (result > 0)
				{
					TempData["message"] = "Added";
				}
				else
				{
					TempData["message"] = "false";
				}
				return RedirectToAction("Index");
            }

            return View(footer);
        }

		
		[HasCredential(ActionId = 7)]
		public ActionResult Edit(int id)
        {
            Footer footer = footerService.GetById(id);
            if (footer == null)
            {
                return HttpNotFound();
            }
            return View(footer);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        [HasCredential(ActionId = 7)]
		public ActionResult Edit([Bind(Include = "ID,Content,Status")] Footer footer)
        {
            if (ModelState.IsValid)
            {
				var result= footerService.Update(footer);
				if (result > 0)
				{
					TempData["message"] = "Added";
				}
				else
				{
					TempData["message"] = "false";
				}
				return RedirectToAction("Index");
            }
            return View(footer);
        }

	
		[HasCredential(ActionId = 8)]
		public ActionResult Delete(int id)
        {
			var result= footerService.Delete(id);
			if (result > 0)
			{
				TempData["message"] = "Added";
			}
			else
			{
				TempData["message"] = "false";
			}
			return RedirectToAction("Index");
        }

       
    }
}

ShopingCart/Areas/Admin/Controllers/SliderController.cs
using Model;
using Service;
using System.Web.Mvc;
using ShopingCart.Common;

namespace ShopingCart.Areas.Admin.Controllers
{
	public class SliderController : BaseController
	{
		private SliderService sliderService;
		public SliderController()
		{
			sliderService = new SliderService();
		}
	
		[HasCredential(ActionId = 19)]
		public ActionResult Index(string searchString, int Page = 1, int PageSize = 10)
		{
			return View(sliderService.Search(searchString,Page,PageSize));
		}
		[HttpGet]
		[HasCredential(ActionId = 20)]
		public ActionResult Create()
		{
			return View();
		}
		[HttpPost]
		[HasCredential(ActionId = 20)]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Slider s)
		{
			if (ModelState.IsValid)
			{
				var result = sliderService.Insert(s);
				if (result > 0)
				{
					TempData["message"] = "Added";
				}
				else
				{
					TempData["message"] = "false";
				}
				return RedirectToAction("Index");
			}
			return View();
		}
		[HttpGet]
		[HasCredential(ActionId = 21)]
		public ActionResult Edit(int id)
		{
			return View(sliderService.GetById(id));
		}
		[HasCredential(ActionId = 21)]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Slider s)
		{
			if (ModelState.IsValid)
			{
				var result = sliderService.Update(s);
				if (result > 0)
				{
					TempData["message"] = "Added";
				}
				else
				{
					TempData["message"] = "false";
				}
				return RedirectToAction("Index");
			}
			return View();
		}
		[HasCredential(ActionId = 22)]
		public ActionResult Delete(int id)
		{
			var result = sliderService.Delete(id);
			if (result > 0)
			{
				TempData["message"] = "Added";
			}
			else
			{
				TempData["message"] = "false";
			}
			return RedirectToAction("Index");
		}
	}
}

ShopingCart/Controllers/LoginController.cs
using BotDetect.Web.Mvc;
using DAL;
using Model;
using Model.ViewModel;
using Service;
using ShopingCart.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;

namespace ShopingCart.Controllers
{
    public class LoginController : Controller
    {
		private UserService _userService;
	
		public LoginController()
		{
			_userService = new UserService();
			
		}


   
        public ActionResult Index()
        {
            return View();
        }
       
		[HttpPost]
		public ActionResult Index(LoginModel model)
		{
			if (ModelState.IsValid)
			{
				var res = _userService.Login(model.UserName, Encryptor.MD5Hash(model.Password));
				if (res)
				{
					var user = _userService.GetByUserName(model.UserName);
                    Session["User"] = user;
                    if (!user.Status)
					{
						ModelState.AddModelError("", "Tài khoản của bạn hiện đang bị khóa");
						return View("Index");
					}

                    if (Session[Common.CommonConstants.SESSION_CART] != null)
                    {
                        return RedirectToAction("Index", "Cart");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
					
				}
				else
				{
					ModelState.AddModelError("", "Tên Tài Khoản Hoặc Mật Khẩu Không Chính Xác");
				}
			}
			return View("Index");
		}
		public ActionResult LogOut()
		{
			Session["User"] = null;
            Session[Common.CommonConstants.SESSION_CART] = null;
			return Redirect("/");
		}
        public ActionResult ForgotPassWord()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPassWord(string EmailAddress)
        {
            string mesage = "";
          
            using (DBEntityContext db = new DBEntityContext())
            {
                var acc = db.Users.Where(x => x.Email == EmailAddress).FirstOrDefault();
                if (acc!=null)
                {
                    string resetCode = Guid.NewGuid().ToString();
                    SendVerificationLinkEmail(acc.Email, resetCode, "ResetPassword");
                    acc.RessetPasswordCode = resetCode;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();
                    mesage = "Chúng tôi đã gửi 1 đường link về tài khoản của bạn để đặt lại mật khẩu";
                }
                else
                {
                    mesage = "Không tìm thấy tài khoản";
                }
            }
            ViewBag.Message = mesage;
            return View();
        }
        [NonAction]
        public void SendVerificationLinkEmail(string EmailAddress, string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/Login/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("minhdang9a8@gmail.com", "Nội Thất Đồ Gỗ");
            var toEmail = new MailAddress(EmailAddress);
            var fromEmailPassword = "minhdang"; 

            string subject = "";
            string body = "";
            if (emailFor == "VerifyAccount")
            {
                subject = "Your account is successfully created!";
                body = "<br/><br/>We are excited to tell you that your Dotnet Awesome account is" +
                    " successfully created. Please click on the below link to verify your account" +
                    " <br/><br/><a href='" + link + "'>" + link + "</a> ";
            }
            else if (emailFor == "ResetPassword")
            {
                subject = "Reset Password";
                body = "Xin Chào ,<br/><br/>Chúng tôi nhận được yêu cầu đặt lại mật khẩu tài khoản của bạn. Vui lòng nhấp vào liên kết dưới đây để thiết lập lại mật khẩu của bạn" +
                    "<br/><br/><a href=" + link + ">Đặt Lại Mật Khẩu</a>";
            }


            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Timeout = 10000,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })

                smtp.Send(message);
        }
        public ActionResult ResetPassword(string id)
        {
            using(DBEntityContext db = new DBEntityContext())
            {
                var user = db.Users.Where(s => s.RessetPasswordCode == id).FirstOrDefault();
                if (user != null)
                {
                    ResetPassWord model = new ResetPassWord();
                    model.ResetCode = id;
                    return View(model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPassword(ResetPassWord model)
        {
            var message = "";
            if (ModelState.IsValid)
            {
                using (DBEntityContext db = new DBEntityContext())
                {
                    var user = db.Users.Where(s => s.RessetPasswordCode == model.ResetCode).FirstOrDefault();
                    if (user !=null)
                    {
                        user.Password = Encryptor.MD5Hash(model.NewPassword);
                        user.RessetPasswordCode = "";
                        db.Configuration.ValidateOnSaveEnabled = false;
                        db.SaveChanges();
                        message = "Cập Nhập Mật Khẩu Thành Công";
                        
                    }

                }
            }
            else
            {
                message = "Cập Nhập Mật Khẩu Thất Bại";
                
            }
            ViewBag.Message = message;
            return View(model);
            
        }


    }
}

ShopingCart/Controllers/OrderController.cs
using Model;
using Service;
using ShopingCart.Common;
using ShopingCart.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ShopingCart.Controllers
{
    public class OrderController : Controller
    {
		private UserService _userService;
		private OrderService _orderService;
		private OrderDetailService _orderDetailService;
		public OrderController()
		{
			_userService = new UserService();
			_orderService = new OrderService();
			_orderDetailService = new OrderDetailService();
		}
        
        public ActionResult Index()
        {
	        if (Session["User"] != null)
			{
				var currentUser =(User)Session["User"];
				var user =_userService.GetById(currentUser.UserId);
				ViewBag.User = user;
			}
            return View();
        }
		[HttpPost]
		public ActionResult Index(Order order)
		{
			if (Session["User"] != null)
			{
				var currentUser = (User)Session["User"];
				var user = _userService.GetById(currentUser.UserId);
				ViewBag.User = user;
			}
			if (ModelState.IsValid)
			{
                var currentUser = (User)Session["User"];
                var cart =(List<CartItem>) Session[Common.CommonConstants.SESSION_CART];
				var orderDetails = new List<OrderDetail>();
				foreach (var item in cart)
				{
					var orderDetail = new OrderDetail {
					Price = (item.Product.Sale_Price !=null&&item.Product.Sale_Price<item.Product.Price) ? float.Parse(item.Product.Sale_Price.ToString()): float.Parse( item.Product.Price.ToString()),
					Product_Id=item.Product.Id,
					Quantity=item.Quantity,
					
					};
					orderDetails.Add(orderDetail);

				}
			    var result=	_orderDetailService.Inserts(order,orderDetails);
                if (result > 0)
                {
                    string header = System.IO.File.ReadAllText(Server.MapPath(@"~/App_Start/header.txt"));
                    string footer = System.IO.File.ReadAllText(Server.MapPath(@"~/App_Start/footer.txt"));
                    string main = String.Format(@"<h2 class='title'>Nội Thất TĐRH -Xác Nhận Đơn Hàng</h2>
                <p>
					<b>Họ tên người nhận:</b>
					<span>{0}</span>
				</p>
				<p>
					<b>Email:</b>
					<span>{1}</span>
				</p>
				<p>
					<b>SĐT:</b>
					<span>{2}</span>
				</p>
				<p>
					<b>Địa chỉ:</b>
					<span>{3}</span>
				</p>
				<p>
					<b>Ngày mua:</b>
					<span>{4}</span>
				</p>", currentUser.FullName, currentUser.Email  , currentUser.Phone, currentUser.Address, DateTime.Now);
                    main += @"<table class='table text-center'>
					<thead>
						<tr>
							<th>Sản phẩm</th>
							<th>Đơn giá</th>
							<th>Số lượng</th>
							<th>Thành tiền</th>
                            <th>Tổng Tiền</th>
						</tr>
					</thead>
					<tbody>";
                    foreach (var item in cart)
                    {
                        var total = 0;
                        var money = (item.Quantity * item.Product.Price);
                        var price = item.Product.Price = (item.Product.Sale_Price != null && item.Product.Sale_Price < item.Product.Price) ? float.Parse(item.Product.Sale_Price.ToString()) : float.Parse(item.Product.Price.ToString());
                        total += (int)money;
                        main += "    <tr>";
                        main += "	 <td>" + item.Product.Name + "</td>";
                        main += "    <td>" + item.Product.Price + " VNĐ</td>";
                        main += "    <td>" + item.Quantity + "</td>";
                        main += "    <td>" + (item.Quantity * price) + "</td>";
                        main += "    <td>" + total + "</td>";
                        main += "</tr>";
                    }
                    main += @"</tbody>
				</table>";
                    
                    TempData["message"] = "Added";
                    TempData["DataSuccess"] = "Đặt hàng thành công";
					Session[Common.CommonConstants.SESSION_CART] = null;
				}
				else
				{
					TempData["message"] = "false";
				}
				return RedirectToAction("Index","Home");
			}
			return View();
		}
    }
}

ShopingCart/Controllers/ResgiterController.cs
using Model;
using Service;
using System.Web.Mvc;
using BotDetect.Web.Mvc;
using ShopingCart.Common;

namespace ShopingCart.Controllers
{
	public class ResgiterController : Controller
	{
		private UserService userService;

		public ResgiterController()
		{
			userService = new UserService();
		}
		
		public ActionResult Index()
		{
			return View();
		}
		[HttpPost]
		[CaptchaValidationActionFilter("CaptchaCode", "registerCaptcha", "Mã Xác Nhận Không Đúng!")]
		public ActionResult Index(User user)
		{
			if (ModelState.IsValid)
			{
				user.Password = Encryptor.MD5Hash(user.Password);
				var result = userService.Insert(user);
				if (result > 0)
				{
					TempData["message"] = "Added";
					TempData["DataSuccess"] = "Đăng ký thành công";
				}
				else if (result == -1)
				{
					ModelState.AddModelError("Username", "Tài Khoản Đã Tồn Tại");
					return View();
				}
				else if (result == -2)
				{
					ModelState.AddModelError("Email", "Email Đã Tồn Tại");
					return View();
				}
				else if (result == -3)
				{
					ModelState.AddModelError("Phone", "Số điện thoại Đã Tồn Tại");
					return View();
				}
				else
				{
					TempData["message"] = "false";
				}
				return RedirectToAction("Index","Home");
			}
			return View();
			
		}
	}
}

ShopingCart/Controllers/SearchController.cs
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using PagedList.Mvc;
using PagedList;

namespace ShopingCart.Controllers
{
    public class SearchController : Controller
    {
        private ProductService service;
        private CategoryService category;
        private DBEntityContext db;
        public SearchController()
        {

            db = new DBEntityContext();
            category = new CategoryService();
            service = new ProductService();
        }
        
		
  
    public ActionResult ResultSearch(string searchString, int?Page)
        {
            ViewBag.ListCategory = category.GetAll();
            ViewBag.searchString = searchString;

            if (Request.HttpMethod!="GET")
            {
                Page = 1;
            }
            int PageSize = 9;
            int pageNumber = (Page ?? 1);



            var lisP = db.Products.Where(s => s.Name.Contains(searchString));
            return View(lisP.OrderBy(x => x.Name).ToPagedList(pageNumber,PageSize));

        }
    }
}

ShopingCart/Views/Shared/Footer.cshtml
@model Model.Footer

    <div class="service-area pt-70 pb-40 gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="single-service mb-30">
                        <div class="service-icon">
                            <i class="pe-7s-world"></i>
                        </div>
                        <div class="service-title">
                            <h3>Dịch vụ chuyên nghiệp</h3>
                            <p>Tư Vấn Thiết Kế Miễn Phí</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-service mb-30">
                        <div class="service-icon">
                            <i class="pe-7s-portfolio"></i>
                        </div>
                        <div class="service-title">
                            <h3>Kinh nghiệm lâu năm</h3>
                            <p>Với nhiều Năm Kinh Nghiệm Trong Lĩnh Vực Nội Thất</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-service mb-30 sm-mrg">
                        <div class="service-icon">
                            <i class="pe-7s-hammer"></i>
                        </div>
                        <div class="service-title">
                            <h3>Thi công nhanh chóng</h3>
                            <p>Thi Công Lắp Đặt Nhanh Chóng Theo</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="single-service mb-30 xs-mrg sm-mrg">
                        <div class="service-icon">
                            <i class="pe-7s-tools"></i>
                        </div>
                        <div class="service-title">
                            <h3>Bảo trì tận tâm</h3>
                            <p>Bảo Trì,Sữa Chữa,Đổi Mới Trong Vòng 5 Năm</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="black-bg">
        <div class="footer-top-area ptb-60">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-4">
                        <div class="footer-widget">
                            <h3 class="footer-title">Liên Hệ Với Chúng Tôi</h3>
                            <div class="footer-contact">
                                <ul>

                                    <li><em class="fa fa-map-marker"></em>Xưởng Sản Xuất:Quận Bình Thạnh <span>Thành Phó Hồ Chí Minh</span></li>
                                    <li><em class="fa fa-phone"></em>Điện Thoại: <a href="tel:0989318744">0989.318.744</a> <span></span></li>
                                    <li><em class="fa fa-envelope-o"></em>Email: <a href="mailto:minhdang9a8@gmail.com">noithatTĐRH@gmail.com</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="footer-widget">
                            <h3 class="footer-title">Về Chúng Tôi</h3>
                            <ul class="block-content">
                                <p style="color:white">
                                    Nội Thất TĐRH là đơn vị thiết kế, thi công nội, ngoại thất và kiến trúc chuyên nghiệp. Với lợi thế là nhà nghiên cứu, sản xuất nội thất thông tinh kết hợp sở hữu xưởng sản xuất, chúng tôi tự tin mang đến những điều tốt đẹp nhất cho các công trình.
                                </p>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <div class="footer-widget">
                            <h3 class="footer-title">Page</h3>
                            <ul class="block-content">
                                <div class="fb-page" data-href="https://www.facebook.com/Shop-n%E1%BB%99i-th%E1%BA%A5t-T%C4%90RH-112528248143080/?ref=pages_you_manage" data-width="" data-height="" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/noithattubephongngoc/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/noithattubephongngoc/">Nội Thất Hồng Ngọc</a></blockquote></div>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-bootom-area ptb-15">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">

                    </div>

                </div>
            </div>
        </div>
        <!-- Messenger Plugin chat Code -->
        <div id="fb-root"></div>

        <!-- Your Plugin chat code -->
        <div id="fb-customer-chat" class="fb-customerchat">
        </div>

        <script>
      var chatbox = document.getElementById('fb-customer-chat');
      chatbox.setAttribute("page_id", "112528248143080");
      chatbox.setAttribute("attribution", "biz_inbox");
        </script>

        <!-- Your SDK code -->
        <script>
      window.fbAsyncInit = function() {
        FB.init({
          xfbml            : true,
          version          : 'v15.0'
        });
      };

      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
        </script>

    </footer>

ShopingCart/Views/Shared/HeaderCart.cshtml
@model List<Model.CartItem>
  @{ 
        double TotalMoney = 0;
  }
    <div class="shopping-cart ml-20 display-inline">
        <a id="" href="/cart"><b>shopping cart</b>@Model.Count</a>
        @if (Model.Count > 0)
        {
           
    <ul>
        @foreach (var item in Model)
        {
             var url = "/chi-tiet-san-pham/" + item.Product.Slug + "-" + item.Product.Id;
            var price = item.Product.Price = (item.Product.Sale_Price != null && item.Product.Sale_Price < item.Product.Price) ? float.Parse(item.Product.Sale_Price.ToString()) : float.Parse(item.Product.Price.ToString());
            var total = (price * item.Quantity);
            TotalMoney += total;
    <li>
        <div class="cart-img">
            <a href="@url"><img width='100px' src="@item.Product.Images" alt="@item.Product.Name" /></a>
        </div>
        <div class="cart-content">
            <h3 style="font-size:20px; color:chocolate">@item.Quantity</h3>
            <span><b>@item.Product.Name</b></span>
            <span class="cart-price">@Convert.ToDecimal(price).ToString("#,##0") VND</span>
        </div>
        <div class="cart-del">
            <a data-id="@item.Product.Id" class="btn-delete"><i class="fa fa-times-circle"></i></a>
        </div>
    </li>


}

        <li>
            <hr class="shipping-border" />
            <div class="shipping">
                <span class="f-left"> Tổng Tiền: @Convert.ToDecimal(TotalMoney).ToString("#,##0") VND</span>
                <span class="f-right cart-price"></span>
            </div>
        </li>
        @Html.ActionLink("Thanh Toán", "Index", "Order")

    </ul>
        }
        else
        {
            <ul>
                        <li>
                        <div class="cart-content">
                            <span><b>Giỏ hàng trống</b></span>
                        </div>
                    </li>
            </ul>
        }

    </div>

ShopingCart/Views/Shared/LoadChilden.cshtml
@model List<Model.Category>
@if ((int)ViewBag.Count > 0)
{

    <ul class="submenu ">
        @foreach (var item in Model)
        {
             var url = "/danh-muc-san-pham/" + item.Slug + "-" + item.ID;
            <li><a href="@url">@item.Name</a></li>
            @Html.Action("LoadChilden", "Home", new { parentID = item.ID })
        }

    </ul>
}

ShopingCart/Views/Shared/MainMenu.cshtml
@using Model;
@model List<Model.Category>
	@{ 
            var user = (User)Session["User"];
	}

	<header class="header-pos">
		<div style="float:right;width:300px;position:relative;position:absolute;top:50px; right: 100px;z-index: 9999">
			<div class="alert alert-success" hidden>

				@if (TempData["DataSuccess"] != null)
				{
					@TempData["DataSuccess"]
				}
				else
				{
					<strong>Lưu thành công!</strong>
				}
			</div>
			<div class="alert alert-danger" hidden>
				<strong>Đã có lỗi xảy ra</strong>
			</div>
		</div>
		<div class="header-area header-middle">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-2 col-sm-3 col-xs-12">
						<div class="logo">
							<a href="/"><img style="margin-top:-20px; width:150px" src="~/Asset/FrontEnd/img/logo/logohutech.png" alt=""></a>
						</div>
					</div>
                    <div class="col-md-10 col-sm-9 col-xs-12 text-right xs-center">
                        <div class="main-menu display-inline hidden-sm hidden-xs">
                            <nav>
                                <ul>
                                    <li>
                                        <a href="/">Trang Chủ</a>
                                    </li>

                                    
        <li>
         <a href="/gioi-thieu">Giới Thiệu</a>
         </li>
                                    

                                    <li>
                                        <a href="/san-pham">Sản Phẩm</a>
                                    </li>

                                   
                  @foreach (var item in Model)
            {
                var url = "/danh-muc-san-pham/" + item.Slug + "-" + item.ID;
        <li>
            <a href="@url">@item.Name</a>
            @Html.Action("LoadChilden", "Home", new { parentID = item.ID })
        </li>
           }
                                    


                          
                                    <li>
                                        <a href="/lien-he/">Liên Hệ</a>
                                    </li>
                                    <li>
                                        <a href="/du-an/">Dự Án</a>
                                    </li>
                                    
                                    
                                </ul>

                            </nav>
                        </div>

                        <div class="search-block-top display-inline">
                            @if(@user != null)
                            {

                                <div><p style="font-weight:700;color:#2c2c2c">Chào!@user.FullName| <a style="color:#2c2c2c" href="@Url.Action("LogOut","Login")">Đăng xuất</a></p></div>
                            }
                            else
                            {

                                <div><p style="font-weight:700;color:#2c2c2c"><a style="color:#2c2c2c" href="@Url.Action("Index","Login")">Đăng nhập</a>  <a style="color:#2c2c2c" href="@Url.Action("Index","Resgiter")"></a></p></div>
                            }


                        </div>
                        <div class="search-block-top display-inline">
                            <div class="icon-search"></div>
                            <div class="toogle-content">

                     
                                    @using (Html.BeginForm("ResultSearch", "Search", FormMethod.Get, new { @id ="searchbox" }))
                                    {
                                        <input type="text" name="searchString" placeholder="Tìm Kiếm Sản Phẩm..." />
                                        <button class="button-search"></button>

                                    }
                              


                                </div>
                        </div>
                        @{ Html.RenderAction("HeaderCart", "Home");}
                    </div>
				</div>
			</div>
		</div>
		<div class="mobile-menu-area visible-sm visible-xs">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<div class="mobile-menu">
							<nav id="mobile-menu-active">
                                <ul>
                                    <li>
                                        <a href="">Trang Chủ</a>
                                    </li>
                                    <li>
                                        <a href="/gioi-thieu">Giới Thiệu</a>
                                    </li>
                                    <li>
                                        <a href="/san-pham">Sản Phẩm</a>
                                    </li>

                                    @foreach (var item in Model)
                                    {
                                        var url = "/danh-muc-san-pham/" + item.Slug + "-" + item.ID;
                                        <li>
                                            <a href="@url">@item.Name</a>
                                            @Html.Action("LoadChilden", "Home", new { parentID = item.ID })
                                        </li>
                                    }
                                    <li>
                                        <a href="">Liên Hệ</a>
                                    </li>


                                </ul>
							</nav>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

ShopingCart/Views/Shared/Slider.cshtml
@model List<Model.Slider>

<div class="slider-container">

    <div id="mainSlider" class="nivoSlider slider-image">
        @foreach (var item in Model)
        {
            <img src="@item.Images" alt="" title="" />
        }

    </div>
</div>